let lastfake = [
  {
    username: '초aaaa기데이터',
    password: '123aaaaaaaaaaaaaaaaaaaaaaaaaaa',
    age: '27',
    address: 'seㅁㅁoul',
    profile_photo: 'https://i.imgur.com/TkIrScD.png',
    nickname: 'nick teㅁㅁst',
    blood: 'ㅁㅁA',
    gender: 'womㅁㅁen',
    drinking: 'noㅁㅁ',
    smoking: 'nㅁㅁo',
    job: '직업ㅁㅁ',
    school: '학력ㅁㅁ',
    hobby: ['책읽ㅁㅁ기', '여ㅁ행', '산ㅁ책'],
    idealType: ['외ㅁ모', '성ㅁ격', 'ㅁ직업'],
    personality: ['활ㅁ발한', '친절ㅁ한'],
  },
  {
    username: 'test',
    password: '123',
    age: '20',
    address: 'seoul',
    profile_photo: 'https://i.imgur.com/TkIrScD.png',
    nickname: 'nick test',
    blood: 'A',
    gender: 'women',
    drinking: 'no',
    smoking: 'no',
    job: '직업',
    school: '학력',
    hobby: ['책읽기', '여행', '산책'],
    idealType: ['외모', '성격', '직업'],
    personality: ['활발한', '친절한'],
  },
];
export default lastfake;
